-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db\tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/page_assessments_projects (
  pap_project_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pap_project_title VARCHAR(255) DEFAULT NULL,
  pap_parent_id INT UNSIGNED DEFAULT NULL,
  UNIQUE INDEX pap_project_title (pap_project_title),
  PRIMARY KEY(pap_project_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/page_assessments (
  pa_page_id INT UNSIGNED NOT NULL,
  pa_project_id INT UNSIGNED NOT NULL,
  pa_class VARCHAR(20) DEFAULT NULL,
  pa_importance VARCHAR(20) DEFAULT NULL,
  pa_page_revision INT UNSIGNED NOT NULL,
  INDEX pa_project (pa_project_id, pa_page_id),
  PRIMARY KEY(pa_page_id, pa_project_id)
) /*$wgDBTableOptions*/;
