-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db\tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE page_assessments_projects (
  pap_project_id SERIAL NOT NULL,
  pap_project_title VARCHAR(255) DEFAULT NULL,
  pap_parent_id INT DEFAULT NULL,
  PRIMARY KEY(pap_project_id)
);

CREATE UNIQUE INDEX pap_project_title ON page_assessments_projects (pap_project_title);


CREATE TABLE page_assessments (
  pa_page_id INT NOT NULL,
  pa_project_id INT NOT NULL,
  pa_class VARCHAR(20) DEFAULT NULL,
  pa_importance VARCHAR(20) DEFAULT NULL,
  pa_page_revision INT NOT NULL,
  PRIMARY KEY(pa_page_id, pa_project_id)
);

CREATE INDEX pa_project ON page_assessments (pa_project_id, pa_page_id);
